### PR TITLE
Fix code styles.

### PR DESCRIPTION
**Pull request by FledgeXu**

### CODE REVIEW

**Comment by livid** [comment]
Is it from your EditorConfig? If possible, could you please also include it in the PR?

**Comment by livid** [comment]
Here is a good read about cosmetic code changes.

https://yihui.org/en/2018/11/cosmetic-changes/

**Comment by FledgeXu** [comment]
Sorry, It's my editor's auto formatting. I will fix it in next commit.

**Comment by FledgeXu** [comment]
The code formatting issue should have been fixed.

**Pull request merged**
